[project]
name = "langraphlearning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=0.3.27",
    "langgraph>=0.6.10",
    "notebook>=7.4.7",
]
